#
# Copyright © 2017-2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += clock.o

obj-y += ccu.o
obj-y += ccu_helpers.o
obj-y += r_ccu_common.o

obj-$(CONFIG_PLATFORM_A23)  += sun8i-a23-ccu.o
obj-$(CONFIG_PLATFORM_A23)  += sun8i-r-ccu.o
obj-$(CONFIG_PLATFORM_A64)  += sun50i-a64-ccu.o
obj-$(CONFIG_PLATFORM_A64)  += sun8i-r-ccu.o
obj-$(CONFIG_PLATFORM_A83T) += sun8i-a83t-ccu.o
obj-$(CONFIG_PLATFORM_A83T) += sun8i-r-ccu.o
obj-$(CONFIG_PLATFORM_H3)   += sun8i-h3-ccu.o
obj-$(CONFIG_PLATFORM_H3)   += sun8i-r-ccu.o
obj-$(CONFIG_PLATFORM_H6)   += sun50i-h6-ccu.o
obj-$(CONFIG_PLATFORM_H6)   += sun50i-h6-r-ccu.o
