#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += clock.o

obj-y += ccu.o
obj-y += ccu_helpers.o

obj-y += sun8i-r-ccu.o
obj-$(CONFIG_PLATFORM_A64)  += sun50i-a64-ccu.o
obj-$(CONFIG_PLATFORM_A83T) += sun8i-a83t-ccu.o
