#
# Copyright © 2020 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

# The first object is used as the linker script.
obj-y += scp.ld.o

obj-y += math.o
obj-y += panic.o
obj-y += runtime.o
obj-y += start.o
