#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += pmic.o

obj-$(CONFIG_PMIC_AXP803) += axp803.o
obj-y                     += dummy.o
