#
# Copyright © 2017-2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += pmic.o

obj-$(CONFIG_PMIC_AXP223) += axp20x.o axp223.o
obj-$(CONFIG_PMIC_AXP803) += axp20x.o axp803.o
obj-$(CONFIG_PMIC_AXP805) += axp20x.o axp805.o
