/*
 * Copyright © 2017-2019 The Crust Firmware Authors.
 * SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
 */

#ifndef PLATFORM_R_CCU_H
#define PLATFORM_R_CCU_H

#include <bitmap.h>
#include <stdint.h>

enum {
	R_CCU_CLOCK_OSC24M,
	R_CCU_CLOCK_OSC32K,
	R_CCU_CLOCK_OSC16M,
	R_CCU_CLOCK_AHB0,
	R_CCU_CLOCK_APB0,
	R_CCU_CLOCK_R_PIO,
	R_CCU_CLOCK_R_CIR,
	R_CCU_CLOCK_R_TIMER,
#if CONFIG_SOC_A64
	R_CCU_CLOCK_R_RSB,
#endif
	R_CCU_CLOCK_R_UART,
	R_CCU_CLOCK_R_I2C,
	R_CCU_CLOCK_R_TWD,
	R_CCU_CLOCK_R_CIR_MOD,
	R_CCU_CLOCK_COUNT
};

#define R_CCU_CLOCK_AHB0_REG  0x0000
#define R_CCU_CLOCK_APB0_REG  0x000c
#define R_CCU_CLOCK_R_CIR_REG 0x0054

#define R_CCU_GATE_BASE       (0x0028 / sizeof(uint32_t))

#define R_CCU_GATE_R_PIO      BITMAP_INDEX(R_CCU_GATE_BASE + 0, 0)
#define R_CCU_GATE_R_CIR      BITMAP_INDEX(R_CCU_GATE_BASE + 0, 1)
#define R_CCU_GATE_R_TIMER    BITMAP_INDEX(R_CCU_GATE_BASE + 0, 2)
#define R_CCU_GATE_R_RSB      BITMAP_INDEX(R_CCU_GATE_BASE + 0, 3)
#define R_CCU_GATE_R_UART     BITMAP_INDEX(R_CCU_GATE_BASE + 0, 4)
#define R_CCU_GATE_R_I2C      BITMAP_INDEX(R_CCU_GATE_BASE + 0, 6)
#define R_CCU_GATE_R_TWD      BITMAP_INDEX(R_CCU_GATE_BASE + 0, 7)

#define R_CCU_RESET_BASE      (0x00b0 / sizeof(uint32_t))

#define R_CCU_RESET_R_CIR     BITMAP_INDEX(R_CCU_RESET_BASE + 0, 1)
#define R_CCU_RESET_R_TIMER   BITMAP_INDEX(R_CCU_RESET_BASE + 0, 2)
#define R_CCU_RESET_R_RSB     BITMAP_INDEX(R_CCU_RESET_BASE + 0, 3)
#define R_CCU_RESET_R_UART    BITMAP_INDEX(R_CCU_RESET_BASE + 0, 4)
#define R_CCU_RESET_R_I2C     BITMAP_INDEX(R_CCU_RESET_BASE + 0, 6)

#endif /* PLATFORM_R_CCU_H */
