#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += css.o
obj-y += css_helpers.o

obj-$(CONFIG_PLATFORM_A64) += sun50i-a64-css.o
obj-$(CONFIG_PLATFORM_H6)  += sun50i-h6-css.o
