#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += clock/
obj-y += css/
obj-y += gpio/
obj-$(CONFIG_I2C) += i2c/
obj-y += irq/
obj-y += mfd/
obj-y += msgbox/
obj-y += pmic/
obj-$(CONFIG_RSB) += rsb/
obj-y += regulator/
obj-y += watchdog/
