#
# Copyright © 2017-2018 The Crust Firmware Authors.
# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
#

subdirs-y += clock
subdirs-y += gpio
subdirs-y += i2c
subdirs-y += irqchip
subdirs-y += msgbox
subdirs-y += regulator
subdirs-y += timer
subdirs-y += watchdog
