#
# Copyright © 2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-$(CONFIG_PLATFORM_A83T) += sun8i-cnt64.o
obj-$(CONFIG_PLATFORM_A64)  += sun8i-cnt64.o
obj-$(CONFIG_PLATFORM_H6)   += sun50i-h6-r-cnt.o
