#
# Copyright © 2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-$(CONFIG_PLATFORM_A23)  += sun6i-a31-cnt64.o
obj-$(CONFIG_PLATFORM_A64)  += sun6i-a31-cnt64.o
obj-$(CONFIG_PLATFORM_A83T) += sun9i-a80-timestamp.o
obj-$(CONFIG_PLATFORM_H3)   += sun6i-a31-cnt64.o
obj-$(CONFIG_PLATFORM_H6)   += sun9i-a80-timestamp.o
