#
# Copyright © 2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-$(CONFIG_PLATFORM_A64)  += sun6i-a31-cnt64.o
obj-$(CONFIG_PLATFORM_H3)   += sun6i-a31-cnt64.o
