#
# Copyright © 2017-2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += watchdog.o

obj-$(CONFIG_WATCHDOG_SUN6I_A31_WDT) += sun6i-a31-wdt.o
obj-$(CONFIG_WATCHDOG_SUN9I_A80_TWD) += sun9i-a80-twd.o
