#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

$(call linker_scripts,crust.ld)

obj-y += console.o
obj-y += debug.o
obj-y += delay.o
obj-y += device.o
obj-y += main.o
obj-y += panic.o
obj-y += scpi.o
obj-y += scpi_cmds.o
obj-y += start.o
obj-y += system_power.o
