#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

$(call linker_scripts,crust.ld)

obj-y += delay.o
obj-y += main.o
obj-y += start.o
obj-y += wallclock.o
