#
# Copyright © 2017-2020 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

# The first object is used as the linker script.
obj-y += crust.ld.o

obj-y += debug/

obj-y += debug.o
obj-y += delay.o
obj-y += device.o
obj-y += main.o
obj-y += panic.o
obj-y += regulator_list.o
obj-y += scpi.o
obj-y += scpi_cmds.o
obj-y += start.o
obj-y += system.o
