#
# Copyright © 2019-2022 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += serial.o uart.o

obj-$(CONFIG_PLATFORM_A23)  += sun8i-a23-uart.o
obj-$(CONFIG_PLATFORM_A83T) += sun8i-a83t-uart.o
obj-$(CONFIG_PLATFORM_H3)   += sun8i-h3-uart.o
obj-$(CONFIG_PLATFORM_H6)   += sun50i-h6-uart.o
obj-$(CONFIG_SOC_A64)       += sun50i-a64-uart.o
obj-$(CONFIG_SOC_H5)        += sun8i-h3-uart.o
