#
# Copyright © 2020 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-$(CONFIG_DEBUG_PRINT_BATTERY) += battery.o
obj-$(CONFIG_DEBUG_PRINT_LATENCY) += latency.o
obj-$(CONFIG_DEBUG_PRINT_SPRS)    += sprs.o
