#
# Copyright © 2017-2018 The Crust Firmware Authors.
# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
#

obj-y += devices.o

$(call add-headers,$(OBJ)/scp.elf,$(subdir)/include)
$(call add-headers,$(OBJ)/host/tools/%.o,$(subdir)/include)
