#
# Copyright © 2017-2018 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

cppflags-y += -I$(SRC)/platform/$(CONFIG_PLATFORM)/include

tools-y += load
tools-y += test
