#
# Copyright © 2017-2020 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += regulator.o

obj-$(CONFIG_REGULATOR_AXP803)  += axp20x.o axp803.o
obj-$(CONFIG_REGULATOR_AXP805)  += axp20x.o axp805.o
obj-$(CONFIG_REGULATOR_SY8106A) += sy8106a.o
