#
# Copyright © 2017-2018 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += regulator.o

obj-$(CONFIG_REGULATOR_AXP803)  += axp803.o
obj-$(CONFIG_REGULATOR_SY8106A) += sy8106a.o
