#
# Copyright © 2017-2020 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y             += regmap.o
obj-$(CONFIG_I2C) += regmap-i2c.o

obj-$(CONFIG_I2C) += sun6i-i2c.o
obj-$(CONFIG_RSB) += sunxi-rsb.o
