/*
 * Copyright © 2017-2019 The Crust Firmware Authors.
 * SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
 */

#ifndef PLATFORM_R_CCU_H
#define PLATFORM_R_CCU_H

enum {
	R_CCU_CLOCK_OSC24M,
	R_CCU_CLOCK_OSC32K,
	R_CCU_CLOCK_OSC16M,
	R_CCU_CLOCK_AHB0,
	R_CCU_CLOCK_APB0,
	R_CCU_CLOCK_R_PIO,
	R_CCU_CLOCK_R_CIR,
	R_CCU_CLOCK_R_TIMER,
	R_CCU_CLOCK_R_RSB,
	R_CCU_CLOCK_R_UART,
	R_CCU_CLOCK_R_I2C,
	R_CCU_CLOCK_R_TWD,
	R_CCU_CLOCK_R_CIR_MOD,
	R_CCU_CLOCK_COUNT
};

#endif /* PLATFORM_R_CCU_H */
